# Generated by Django 5.2.8 on 2025-11-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('ciencia', 'Ciencia'), ('historia', 'Historia'), ('biografia', 'Biografía'), ('fantasia', 'Fantasía'), ('romance', 'Romance'), ('terror', 'Terror'), ('poesia', 'Poesía'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
