# Generated by Django 5.2.8 on 2025-11-29 15:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgb', '0002_alter_libro_options_alter_prestamo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
